name = "ADSSimulation"
uuid = "17116840-8c5d-4c3b-9d60-eaecefa0264a"
authors = ["Alec Bills <abills@andrew.cmu.edu>"]
version = "0.1.0"

[deps]
CSV = "336ed68f-0bac-5ca0-87d4-7b16caf5d00b"
CellFitElectrolyte = "db930f26-d6e4-4d2e-b115-89fcca269ba4"
ComponentArrays = "b0b7db55-cfe3-40fc-9ded-d10e2dbeff66"
CondaPkg = "992eb4ea-22a4-4c89-a5bb-47a3300528ab"
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
Distributions = "31c24e10-a181-5473-b8eb-7969acd0382f"
JLD2 = "033835bb-8acc-5ee8-8aae-3f567f8a3819"
JuMP = "4076af6c-e467-56ae-b986-b466b2749572"
OCV = "b2dcbbec-23b4-43a7-a569-d41358da336e"
PythonCall = "6099a3de-0909-46bc-b1f4-468b9a2dfc0d"
PythonPlot = "274fc56d-3b97-40fa-a1cd-1b4a50311bf9"
Turing = "fce5fe82-541a-59a6-adf8-730c64b5f9a0"
